// Code generated by tools/acore/gen_basestats. DO NOT EDIT.

// Level 80 player stats from AzerothCore: the gt*.dbc game tables, the world database's
// player_class_stats and player_race_stats, and Unit.h, StatSystem.cpp and Player.cpp.

package core

import (
	"github.com/wowsims/wotlk/sim/core/proto"
	"github.com/wowsims/wotlk/sim/core/stats"
)

// CombatRating is the server's CombatRating enum.
type CombatRating int32

const (
	CRWeaponSkill CombatRating = iota
	CRDefenseSkill
	CRDodge
	CRParry
	CRBlock
	CRHitMelee
	CRHitRanged
	CRHitSpell
	CRCritMelee
	CRCritRanged
	CRCritSpell
	CRHitTakenMelee
	CRHitTakenRanged
	CRHitTakenSpell
	CRCritTakenMelee
	CRCritTakenRanged
	CRCritTakenSpell
	CRHasteMelee
	CRHasteRanged
	CRHasteSpell
	CRWeaponSkillMainhand
	CRWeaponSkillOffhand
	CRWeaponSkillRanged
	CRExpertise
	CRArmorPenetration
	NumCombatRatings
)

// Rating for 1%, or for one point of defense or expertise. Every class converts these the same.
const (
	ExpertisePerQuarterPercentReduction    = 8.197496
	HasteRatingPerHastePercent             = 32.78999
	CritRatingPerCritChance                = 45.905987
	MeleeHitRatingPerHitChance             = 32.78999
	SpellHitRatingPerHitChance             = 26.231993
	DefenseRatingPerDefense                = 4.918498
	DodgeRatingPerDodgeChance              = 45.250187
	ParryRatingPerParryChance              = 45.250187
	BlockRatingPerBlockChance              = 16.394995
	ResilienceRatingPerCritReductionChance = 94.271225
)

// Every class with mana shares these.
const (
	// Spell crit chance per point of intellect (gtChanceToSpellCrit).
	SpellCritPerIntellect = 6e-05
	// Mana per second per point of spirit, times √intellect (gtRegenMPPerSpt).
	ManaRegenPerSpirit = 0.003345
)

// CombatRatingBase is gtCombatRatings: rating for 1% before the class scalar.
var CombatRatingBase = [NumCombatRatings]float64{
	CRWeaponSkill:         8.197496,
	CRDefenseSkill:        4.918498,
	CRDodge:               45.250187,
	CRParry:               45.250187,
	CRBlock:               16.394995,
	CRHitMelee:            32.78999,
	CRHitRanged:           32.78999,
	CRHitSpell:            26.231993,
	CRCritMelee:           45.905987,
	CRCritRanged:          45.905987,
	CRCritSpell:           45.905987,
	CRHitTakenMelee:       32.78999,
	CRHitTakenRanged:      32.78999,
	CRHitTakenSpell:       26.231993,
	CRCritTakenMelee:      94.271225,
	CRCritTakenRanged:     94.271225,
	CRCritTakenSpell:      94.271225,
	CRHasteMelee:          32.78999,
	CRHasteRanged:         32.78999,
	CRHasteSpell:          32.78999,
	CRWeaponSkillMainhand: 8.197496,
	CRWeaponSkillOffhand:  8.197496,
	CRWeaponSkillRanged:   8.197496,
	CRExpertise:           8.197496,
	CRArmorPenetration:    15.3953,
}

// CombatRatingClassScalars is gtOCTClassCombatRatingScalar, in CombatRating order. A class needs
// CombatRatingBase/scalar rating for 1%.
var CombatRatingClassScalars = map[proto.Class][NumCombatRatings]float64{
	proto.Class_ClassWarrior:     {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.1},
	proto.Class_ClassPaladin:     {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.3, 1, 1, 1, 1, 1, 1, 1.1},
	proto.Class_ClassHunter:      {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.1},
	proto.Class_ClassRogue:       {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.1},
	proto.Class_ClassPriest:      {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.1},
	proto.Class_ClassDeathknight: {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.3, 1, 1, 1, 1, 1, 1, 1.1},
	proto.Class_ClassShaman:      {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.3, 1, 1, 1, 1, 1, 1, 1.1},
	proto.Class_ClassMage:        {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.1},
	proto.Class_ClassWarlock:     {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.1},
	proto.Class_ClassDruid:       {1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.3, 1, 1, 1, 1, 1, 1, 1.1},
}

// ClassBaseStats is player_class_stats.
var ClassBaseStats = map[proto.Class]stats.Stats{
	proto.Class_ClassWarrior:     {stats.Health: 8121, stats.Mana: 0, stats.Strength: 174, stats.Agility: 113, stats.Stamina: 159, stats.Intellect: 36, stats.Spirit: 59},
	proto.Class_ClassPaladin:     {stats.Health: 6934, stats.Mana: 4394, stats.Strength: 151, stats.Agility: 90, stats.Stamina: 143, stats.Intellect: 98, stats.Spirit: 105},
	proto.Class_ClassHunter:      {stats.Health: 7324, stats.Mana: 5046, stats.Strength: 74, stats.Agility: 181, stats.Stamina: 128, stats.Intellect: 90, stats.Spirit: 97},
	proto.Class_ClassRogue:       {stats.Health: 7604, stats.Mana: 0, stats.Strength: 113, stats.Agility: 189, stats.Stamina: 105, stats.Intellect: 43, stats.Spirit: 67},
	proto.Class_ClassPriest:      {stats.Health: 6960, stats.Mana: 3863, stats.Strength: 43, stats.Agility: 51, stats.Stamina: 67, stats.Intellect: 174, stats.Spirit: 181},
	proto.Class_ClassDeathknight: {stats.Health: 8121, stats.Mana: 0, stats.Strength: 175, stats.Agility: 112, stats.Stamina: 160, stats.Intellect: 35, stats.Spirit: 59},
	proto.Class_ClassShaman:      {stats.Health: 6939, stats.Mana: 4396, stats.Strength: 120, stats.Agility: 74, stats.Stamina: 136, stats.Intellect: 128, stats.Spirit: 143},
	proto.Class_ClassMage:        {stats.Health: 6963, stats.Mana: 3268, stats.Strength: 36, stats.Agility: 43, stats.Stamina: 59, stats.Intellect: 181, stats.Spirit: 174},
	proto.Class_ClassWarlock:     {stats.Health: 7136, stats.Mana: 3856, stats.Strength: 59, stats.Agility: 67, stats.Stamina: 89, stats.Intellect: 159, stats.Spirit: 166},
	proto.Class_ClassDruid:       {stats.Health: 7417, stats.Mana: 3496, stats.Strength: 89, stats.Agility: 82, stats.Stamina: 98, stats.Intellect: 143, stats.Spirit: 159},
}

// RaceStatOffsets is player_race_stats.
var RaceStatOffsets = map[proto.Race]stats.Stats{
	proto.Race_RaceHuman:    {stats.Strength: 0, stats.Agility: 0, stats.Stamina: 0, stats.Intellect: 0, stats.Spirit: 0},
	proto.Race_RaceOrc:      {stats.Strength: 3, stats.Agility: -3, stats.Stamina: 1, stats.Intellect: -3, stats.Spirit: 2},
	proto.Race_RaceDwarf:    {stats.Strength: 5, stats.Agility: -4, stats.Stamina: 1, stats.Intellect: -1, stats.Spirit: -1},
	proto.Race_RaceNightElf: {stats.Strength: -4, stats.Agility: 4, stats.Stamina: 0, stats.Intellect: 0, stats.Spirit: 0},
	proto.Race_RaceUndead:   {stats.Strength: -1, stats.Agility: -2, stats.Stamina: 0, stats.Intellect: -2, stats.Spirit: 5},
	proto.Race_RaceTauren:   {stats.Strength: 5, stats.Agility: -4, stats.Stamina: 1, stats.Intellect: -4, stats.Spirit: 2},
	proto.Race_RaceGnome:    {stats.Strength: -5, stats.Agility: 2, stats.Stamina: 0, stats.Intellect: 3, stats.Spirit: 0},
	proto.Race_RaceTroll:    {stats.Strength: 1, stats.Agility: 2, stats.Stamina: 0, stats.Intellect: -4, stats.Spirit: 1},
	proto.Race_RaceBloodElf: {stats.Strength: -3, stats.Agility: 2, stats.Stamina: 0, stats.Intellect: 3, stats.Spirit: -2},
	proto.Race_RaceDraenei:  {stats.Strength: 1, stats.Agility: -3, stats.Stamina: 0, stats.Intellect: 0, stats.Spirit: 2},
}

// ClassStatScaling comes from the gt crit tables, the attack power formulas in StatSystem.cpp,
// and the dodge and diminishing returns tables in Player.cpp and StatSystem.cpp.
var ClassStatScaling = map[proto.Class]StatScaling{
	proto.Class_ClassWarrior: {
		MeleeCritBase:       0.031891,
		MeleeCritPerAgility: 0.00016,
		SpellCritBase:       0,
		MeleeAttackPower:    AttackPowerFormula{PerLevel: 3, PerStrength: 2, PerAgility: 0, Base: -20},
		RangedAttackPower:   AttackPowerFormula{PerLevel: 1, PerStrength: 0, PerAgility: 1, Base: -10},
		DodgeBase:           0.03664,
		CritToDodge:         0.7391305,
		DodgeCap:            88.12902,
		ParryCap:            47.003525,
		MissCap:             16,
		DiminishingK:        0.956,
	},
	proto.Class_ClassPaladin: {
		MeleeCritBase:       0.032685,
		MeleeCritPerAgility: 0.000192,
		SpellCritBase:       0.033355,
		MeleeAttackPower:    AttackPowerFormula{PerLevel: 3, PerStrength: 2, PerAgility: 0, Base: -20},
		RangedAttackPower:   AttackPowerFormula{PerLevel: 0, PerStrength: 0, PerAgility: 1, Base: -10},
		DodgeBase:           0.034943,
		CritToDodge:         0.86956525,
		DodgeCap:            88.12902,
		ParryCap:            47.003525,
		MissCap:             16,
		DiminishingK:        0.956,
	},
	proto.Class_ClassHunter: {
		MeleeCritBase:       -0.01532,
		MeleeCritPerAgility: 0.00012,
		SpellCritBase:       0.03602,
		MeleeAttackPower:    AttackPowerFormula{PerLevel: 2, PerStrength: 1, PerAgility: 1, Base: -20},
		RangedAttackPower:   AttackPowerFormula{PerLevel: 2, PerStrength: 0, PerAgility: 1, Base: -10},
		DodgeBase:           -0.040873,
		CritToDodge:         0.9652174,
		DodgeCap:            145.56041,
		ParryCap:            145.56041,
		MissCap:             16,
		DiminishingK:        0.988,
	},
	proto.Class_ClassRogue: {
		MeleeCritBase:       -0.00295,
		MeleeCritPerAgility: 0.00012,
		SpellCritBase:       0,
		MeleeAttackPower:    AttackPowerFormula{PerLevel: 2, PerStrength: 1, PerAgility: 1, Base: -20},
		RangedAttackPower:   AttackPowerFormula{PerLevel: 1, PerStrength: 0, PerAgility: 1, Base: -10},
		DodgeBase:           0.020957,
		CritToDodge:         1.7391305,
		DodgeCap:            145.56041,
		ParryCap:            145.56041,
		MissCap:             16,
		DiminishingK:        0.988,
	},
	proto.Class_ClassPriest: {
		MeleeCritBase:       0.031765,
		MeleeCritPerAgility: 0.000192,
		SpellCritBase:       0.012375,
		MeleeAttackPower:    AttackPowerFormula{PerLevel: 0, PerStrength: 1, PerAgility: 0, Base: -10},
		RangedAttackPower:   AttackPowerFormula{PerLevel: 0, PerStrength: 0, PerAgility: 1, Base: -10},
		DodgeBase:           0.034178,
		CritToDodge:         0.86956525,
		DodgeCap:            150.37595,
		ParryCap:            0,
		MissCap:             16,
		DiminishingK:        0.983,
	},
	proto.Class_ClassDeathknight: {
		MeleeCritBase:       0.031891,
		MeleeCritPerAgility: 0.00016,
		SpellCritBase:       0,
		MeleeAttackPower:    AttackPowerFormula{PerLevel: 3, PerStrength: 2, PerAgility: 0, Base: -20},
		RangedAttackPower:   AttackPowerFormula{PerLevel: 0, PerStrength: 0, PerAgility: 1, Base: -10},
		DodgeBase:           0.03664,
		CritToDodge:         0.7391305,
		DodgeCap:            88.12902,
		ParryCap:            47.003525,
		MissCap:             16,
		DiminishingK:        0.956,
	},
	proto.Class_ClassShaman: {
		MeleeCritBase:       0.02922,
		MeleeCritPerAgility: 0.00012,
		SpellCritBase:       0.02201,
		MeleeAttackPower:    AttackPowerFormula{PerLevel: 2, PerStrength: 1, PerAgility: 1, Base: -20},
		RangedAttackPower:   AttackPowerFormula{PerLevel: 0, PerStrength: 0, PerAgility: 1, Base: -10},
		DodgeBase:           0.02108,
		CritToDodge:         1.3913044,
		DodgeCap:            145.56041,
		ParryCap:            145.56041,
		MissCap:             16,
		DiminishingK:        0.988,
	},
	proto.Class_ClassMage: {
		MeleeCritBase:       0.03454,
		MeleeCritPerAgility: 0.000196,
		SpellCritBase:       0.009075,
		MeleeAttackPower:    AttackPowerFormula{PerLevel: 0, PerStrength: 1, PerAgility: 0, Base: -10},
		RangedAttackPower:   AttackPowerFormula{PerLevel: 0, PerStrength: 0, PerAgility: 1, Base: -10},
		DodgeBase:           0.036587,
		CritToDodge:         0.86956525,
		DodgeCap:            150.37595,
		ParryCap:            0,
		MissCap:             16,
		DiminishingK:        0.983,
	},
	proto.Class_ClassWarlock: {
		MeleeCritBase:       0.02622,
		MeleeCritPerAgility: 0.000198,
		SpellCritBase:       0.017,
		MeleeAttackPower:    AttackPowerFormula{PerLevel: 0, PerStrength: 1, PerAgility: 0, Base: -10},
		RangedAttackPower:   AttackPowerFormula{PerLevel: 0, PerStrength: 0, PerAgility: 1, Base: -10},
		DodgeBase:           0.024211,
		CritToDodge:         0.8434783,
		DodgeCap:            150.37595,
		ParryCap:            0,
		MissCap:             16,
		DiminishingK:        0.983,
	},
	proto.Class_ClassDruid: {
		MeleeCritBase:       0.074755,
		MeleeCritPerAgility: 0.00012,
		SpellCritBase:       0.018515,
		MeleeAttackPower:    AttackPowerFormula{PerLevel: 0, PerStrength: 2, PerAgility: 0, Base: -20},
		RangedAttackPower:   AttackPowerFormula{PerLevel: 0, PerStrength: 0, PerAgility: 1, Base: -10},
		DodgeBase:           0.056097,
		CritToDodge:         1.7391305,
		DodgeCap:            116.89071,
		ParryCap:            0,
		MissCap:             16,
		DiminishingK:        0.972,
	},
}
