// Code generated by tools/acore/gen_server_defaults. DO NOT EDIT.

// The live AzerothCore config: worldserver.conf.dist, the mod-spell-tweaks, mod-dungeon-scale and
// mod-reforging conf.dist files, and configurationOverrides/{ServerPerformance,SpellTweaks,DungeonScale}.env.

package core

import (
	"github.com/wowsims/wotlk/sim/core/proto"
	googleProto "google.golang.org/protobuf/proto"
)

// LiveServerDefaults is the live server's value for every ServerSettings field. A dungeon scale
// size set only holds what the config sets; the rest falls back to Raid or RaidHeroic.
func LiveServerDefaults() *proto.ServerSettings {
	return &proto.ServerSettings{
		MapUpdateIntervalMs: googleProto.Int32(100),
		SpellTweaks: &proto.SpellTweaksSettings{
			Enable:                    googleProto.Bool(true),
			ExoticPetDamagePct:        googleProto.Float64(0),
			HunterPetHaste:            googleProto.Bool(true),
			HunterPetArmorPen:         googleProto.Bool(true),
			DkGhoulArmorPen:           googleProto.Bool(true),
			FeralSpiritHaste:          googleProto.Bool(true),
			DiseaseHaste:              googleProto.Bool(true),
			DeadlyPoisonMurder:        googleProto.Bool(true),
			RuptureWeaponExpertise:    googleProto.Bool(true),
			RendTrauma:                googleProto.Bool(true),
			BalanceDotScaling:         googleProto.Bool(true),
			TitansGripNoDamagePenalty: googleProto.Bool(true),
			OmenClarityFaerieFire:     googleProto.Bool(true),
		},
		DungeonScale: &proto.DungeonScaleSettings{
			Raid:           &proto.DungeonScaleModifiers{Global: googleProto.Float64(1), Health: googleProto.Float64(1), Armor: googleProto.Float64(1), Damage: googleProto.Float64(1)},
			RaidBoss:       &proto.DungeonScaleModifiers{Global: googleProto.Float64(1), Health: googleProto.Float64(1.2), Armor: googleProto.Float64(1), Damage: googleProto.Float64(1)},
			RaidHeroic:     &proto.DungeonScaleModifiers{Global: googleProto.Float64(1), Health: googleProto.Float64(1), Armor: googleProto.Float64(1), Damage: googleProto.Float64(1)},
			RaidHeroicBoss: &proto.DungeonScaleModifiers{Global: googleProto.Float64(1), Health: googleProto.Float64(1.2), Armor: googleProto.Float64(1), Damage: googleProto.Float64(1)},
		},
		Reforge: &proto.ReforgeSettings{Enable: googleProto.Bool(true), Percentage: googleProto.Float64(40), StatTypes: []int32{6, 13, 14, 31, 32, 36, 37}},
	}
}

// DungeonScale.MinHPModifier and DungeonScale.MinDamageModifier: the lowest a health or damage
// multiplier goes.
const (
	DungeonScaleMinHealthModifier = 0.01
	DungeonScaleMinDamageModifier = 0.01
)

// What mod-reforging's item_reforge.h lets Reforging.Percentage and Reforging.ReforgeableStats ask
// for: a percentage outside the range falls back to the default, and a stat list longer than
// MaxReforgeableStatTypes ends up empty, which turns reforging off.
const (
	ReforgeMinPercentage     = 10
	ReforgeMaxPercentage     = 90
	ReforgeDefaultPercentage = 40
	MaxReforgeableStatTypes  = 15
)
