package core

import (
	"fmt"
	"math"
	"sort"
	"sync"
	"time"

	"github.com/wowsims/wotlk/sim/core/serverdata"
	"github.com/wowsims/wotlk/sim/core/stats"
)

type ApplySpellResults func(sim *Simulation, target *Unit, spell *Spell)
type ExpectedDamageCalculator func(sim *Simulation, target *Unit, spell *Spell, useSnapshot bool) *SpellResult
type CanCastCondition func(sim *Simulation, target *Unit) bool

type SpellConfig struct {
	// See definition of Spell (below) for comments on these.
	ActionID
	SpellSchool  SpellSchool
	ProcMask     ProcMask
	Flags        SpellFlag
	MissileSpeed float64
	BaseCost     float64
	MetricSplits int

	ManaCost   ManaCostOptions
	EnergyCost EnergyCostOptions
	RageCost   RageCostOptions
	RuneCost   RuneCostOptions
	FocusCost  FocusCostOptions

	Cast               CastConfig
	ExtraCastCondition CanCastCondition

	BonusHitRating       float64
	BonusCritRating      float64
	BonusSpellPower      float64
	BonusExpertiseRating float64
	BonusArmorPenRating  float64

	DamageMultiplier         float64
	DamageMultiplierAdditive float64
	CritMultiplier           float64

	ThreatMultiplier float64

	FlatThreatBonus float64

	// Performs the actions of this spell.
	ApplyEffects ApplySpellResults

	// Optional field. Calculates expected average damage.
	ExpectedInitialDamage ExpectedDamageCalculator
	ExpectedTickDamage    ExpectedDamageCalculator

	Dot    DotConfig
	Hot    DotConfig
	Shield ShieldConfig

	RelatedAuras []AuraArray
}

type Spell struct {
	// ID for this spell.
	ActionID

	// The unit who will perform this spell.
	Unit *Unit

	// Fire, Frost, Shadow, etc.
	SpellSchool SpellSchool
	SchoolIndex stats.SchoolIndex

	// Controls which effects can proc from this spell.
	ProcMask ProcMask

	// Flags
	Flags SpellFlag

	// Speed in yards/second. Spell missile speeds can be found in the game data.
	// Example: https://wow.tools/dbc/?dbc=spellmisc&build=3.4.0.44996
	MissileSpeed float64

	ResourceMetrics *ResourceMetrics
	healthMetrics   []*ResourceMetrics

	Cost               SpellCost // Cost for the spell.
	DefaultCast        Cast      // Default cast parameters with all static effects applied.
	CD                 Cooldown
	SharedCD           Cooldown
	ExtraCastCondition CanCastCondition

	castTimeFn func(spell *Spell) time.Duration // allows to override CastTime()

	// Performs a cast of this spell.
	castFn CastSuccessFunc

	SpellMetrics      []SpellMetrics
	splitSpellMetrics [][]SpellMetrics // Used to split metrics by some condition.
	casts             int              // Sum of casts on all targets, for efficient CPM calculation

	// Performs the actions of this spell.
	ApplyEffects ApplySpellResults

	// Optional field. Calculates expected average damage.
	expectedInitialDamageInternal ExpectedDamageCalculator
	expectedTickDamageInternal    ExpectedDamageCalculator

	// The current or most recent cast data.
	CurCast Cast

	BonusHitRating           float64
	BonusCritRating          float64
	BonusSpellPower          float64
	BonusExpertiseRating     float64
	BonusArmorPenRating      float64
	CastTimeMultiplier       float64
	CostMultiplier           float64
	DamageMultiplier         float64
	DamageMultiplierAdditive float64
	CritMultiplier           float64

	// Multiplier for all threat generated by this effect.
	ThreatMultiplier float64

	// Adds a fixed amount of threat to this spell, before multipliers.
	FlatThreatBonus float64

	initialBonusHitRating           float64
	initialBonusCritRating          float64
	initialBonusSpellPower          float64
	initialDamageMultiplier         float64
	initialDamageMultiplierAdditive float64
	initialCritMultiplier           float64
	initialThreatMultiplier         float64
	// Note that bonus expertise and armor pen are static, so we don't bother resetting them.

	resultCache SpellResult

	dots   DotArray
	aoeDot *Dot

	shields    ShieldArray
	selfShield *Shield

	// Per-target auras that are related to this spell, usually buffs or debuffs applied by the spell.
	RelatedAuras []AuraArray

	serverSpell     *serverdata.Spell
	serverConflicts []ServerConflict
	timing          castTiming
}

func (unit *Unit) OnSpellRegistered(handler SpellRegisteredHandler) {
	for _, spell := range unit.Spellbook {
		handler(spell)
	}
	unit.spellRegistrationHandlers = append(unit.spellRegistrationHandlers, handler)
}

// Registers a new spell to the unit. Returns the newly created spell.
func (unit *Unit) RegisterSpell(config SpellConfig) *Spell {
	if len(unit.Spellbook) > 100 {
		panic(fmt.Sprintf("Over 100 registered spells when registering %s! There is probably a spell being registered every iteration.", config.ActionID))
	}

	// Default the other damage multiplier to 1 if only one or the other is set.
	if config.DamageMultiplier != 0 && config.DamageMultiplierAdditive == 0 {
		config.DamageMultiplierAdditive = 1
	} else if config.DamageMultiplierAdditive != 0 && config.DamageMultiplier == 0 {
		config.DamageMultiplier = 1
	}

	if (config.DamageMultiplier != 0 || config.ThreatMultiplier != 0) && config.ProcMask == ProcMaskUnknown {
		panic("ProcMask for spell " + config.ActionID.String() + " not set")
	}

	if (config.DamageMultiplier != 0 || config.ThreatMultiplier != 0) && config.SpellSchool == SpellSchoolNone {
		panic("SpellSchool for spell " + config.ActionID.String() + " not set")
	}

	if config.Cast.CD.Timer != nil && config.Cast.CD.Duration == 0 {
		panic("Cast.CD w/o Duration specified for spell " + config.ActionID.String())
	}

	if config.Cast.SharedCD.Timer != nil && config.Cast.SharedCD.Duration == 0 {
		panic("Cast.SharedCD w/o Duration specified for spell " + config.ActionID.String())
	}

	if config.Cast.CastTime == nil {
		config.Cast.CastTime = func(spell *Spell) time.Duration {
			return spell.timing.castTime(spell.Unit, spell.DefaultCast.CastTime, spell)
		}
	}

	spell := &Spell{
		ActionID:     config.ActionID,
		Unit:         unit,
		SpellSchool:  config.SpellSchool,
		ProcMask:     config.ProcMask,
		Flags:        config.Flags,
		MissileSpeed: config.MissileSpeed,

		DefaultCast:        config.Cast.DefaultCast,
		CD:                 config.Cast.CD,
		SharedCD:           config.Cast.SharedCD,
		ExtraCastCondition: config.ExtraCastCondition,

		castTimeFn: config.Cast.CastTime,

		ApplyEffects: config.ApplyEffects,

		expectedInitialDamageInternal: config.ExpectedInitialDamage,
		expectedTickDamageInternal:    config.ExpectedTickDamage,

		BonusHitRating:           config.BonusHitRating,
		BonusCritRating:          config.BonusCritRating,
		BonusSpellPower:          config.BonusSpellPower,
		BonusExpertiseRating:     config.BonusExpertiseRating,
		BonusArmorPenRating:      config.BonusArmorPenRating,
		CastTimeMultiplier:       1,
		CostMultiplier:           1,
		DamageMultiplier:         config.DamageMultiplier,
		DamageMultiplierAdditive: config.DamageMultiplierAdditive,
		CritMultiplier:           config.CritMultiplier,

		ThreatMultiplier: config.ThreatMultiplier,
		FlatThreatBonus:  config.FlatThreatBonus,

		splitSpellMetrics: make([][]SpellMetrics, max(1, config.MetricSplits)),

		RelatedAuras: config.RelatedAuras,
	}

	switch {
	case spell.SpellSchool.Matches(SpellSchoolPhysical):
		spell.SchoolIndex = stats.SchoolIndexPhysical
	case spell.SpellSchool.Matches(SpellSchoolArcane):
		spell.SchoolIndex = stats.SchoolIndexArcane
	case spell.SpellSchool.Matches(SpellSchoolFire):
		spell.SchoolIndex = stats.SchoolIndexFire
	case spell.SpellSchool.Matches(SpellSchoolFrost):
		spell.SchoolIndex = stats.SchoolIndexFrost
	case spell.SpellSchool.Matches(SpellSchoolHoly):
		spell.SchoolIndex = stats.SchoolIndexHoly
	case spell.SpellSchool.Matches(SpellSchoolNature):
		spell.SchoolIndex = stats.SchoolIndexNature
	case spell.SpellSchool.Matches(SpellSchoolShadow):
		spell.SchoolIndex = stats.SchoolIndexShadow
	}

	// newXXXCost() all update spell.DefaultCast.Cost
	if config.ManaCost.BaseCost != 0 || config.ManaCost.FlatCost != 0 {
		spell.Cost = newManaCost(spell, config.ManaCost)
	} else if config.EnergyCost.Cost != 0 {
		spell.Cost = newEnergyCost(spell, config.EnergyCost)
	} else if config.RageCost.Cost != 0 {
		spell.Cost = newRageCost(spell, config.RageCost)
	} else if config.RuneCost.BloodRuneCost != 0 || config.RuneCost.FrostRuneCost != 0 || config.RuneCost.UnholyRuneCost != 0 || config.RuneCost.RunicPowerCost != 0 || config.RuneCost.RunicPowerGain != 0 {
		spell.Cost = newRuneCost(spell, config.RuneCost)
	} else if config.FocusCost.Cost != 0 {
		spell.Cost = newFocusCost(spell, config.FocusCost)
	}

	// before the dots, which read Channeled, and before the cast function is picked
	spell.applyServerData(&config.Cast)

	spell.createDots(config.Dot, false)
	spell.createDots(config.Hot, true)
	spell.createShields(config.Shield)

	var emptyCast Cast

	if spell.DefaultCast == emptyCast && spell.Cost != nil {
		panic("Empty DefaultCast with a cost for spell " + config.ActionID.String())
	}

	if spell.DefaultCast.GCD == 0 && spell.DefaultCast.CastTime == 0 {
		config.Cast.IgnoreHaste = true
	}
	spell.timing = newCastTiming(spell, config.Cast.IgnoreHaste)

	if spell.DefaultCast == emptyCast {
		if config.ExtraCastCondition == nil && config.Cast.CD.Timer == nil && config.Cast.SharedCD.Timer == nil {
			spell.castFn = spell.makeCastFuncAutosOrProcs()
		} else {
			spell.castFn = spell.makeCastFuncSimple()
		}
	} else {
		spell.castFn = spell.makeCastFunc(config.Cast)
	}

	if spell.ApplyEffects == nil {
		spell.ApplyEffects = func(*Simulation, *Unit, *Spell) {}
	}

	unit.Spellbook = append(unit.Spellbook, spell)

	for _, handler := range unit.spellRegistrationHandlers {
		handler(spell)
	}

	if unit.Env != nil && unit.Env.IsFinalized() {
		spell.finalize()
	}

	return spell
}

// Returns the first registered spell with the given ID, or nil if there are none.
func (unit *Unit) GetSpell(actionID ActionID) *Spell {
	for _, spell := range unit.Spellbook {
		if spell.ActionID.SameAction(actionID) {
			return spell
		}
	}
	return nil
}

// Retrieves an existing spell with the same ID as the config uses, or registers it if there is none.
func (unit *Unit) GetOrRegisterSpell(config SpellConfig) *Spell {
	registered := unit.GetSpell(config.ActionID)
	if registered == nil {
		return unit.RegisterSpell(config)
	} else {
		return registered
	}
}

func (spell *Spell) Dot(target *Unit) *Dot {
	return spell.dots.Get(target)
}
func (spell *Spell) CurDot() *Dot {
	return spell.dots.Get(spell.Unit.CurrentTarget)
}
func (spell *Spell) AOEDot() *Dot {
	return spell.aoeDot
}
func (spell *Spell) Hot(target *Unit) *Dot {
	return spell.dots.Get(target)
}
func (spell *Spell) CurHot() *Dot {
	return spell.dots.Get(spell.Unit.CurrentTarget)
}
func (spell *Spell) AOEHot() *Dot {
	return spell.aoeDot
}
func (spell *Spell) SelfHot() *Dot {
	return spell.aoeDot
}
func (spell *Spell) Shield(target *Unit) *Shield {
	return spell.shields.Get(target)
}
func (spell *Spell) SelfShield() *Shield {
	return spell.selfShield
}

// Metrics for the current iteration
func (spell *Spell) CurDamagePerCast() float64 {
	if spell.SpellMetrics[0].Casts == 0 {
		return 0
	} else {
		casts := int32(0)
		damage := 0.0
		for _, opponent := range spell.Unit.GetOpponents() {
			casts += spell.SpellMetrics[opponent.UnitIndex].Casts
			damage += spell.SpellMetrics[opponent.UnitIndex].TotalDamage
		}
		return damage / float64(casts)
	}
}

// Current casts per minute
func (spell *Spell) CurCPM(sim *Simulation) float64 {
	if sim.CurrentTime <= 0 {
		return 0
	}
	casts := float64(spell.casts)
	minutes := float64(sim.CurrentTime) / float64(time.Minute)
	return casts / minutes
}

func (spell *Spell) finalize() {
	// Assert that user doesn't set dynamic fields during static initialization.
	if spell.CastTimeMultiplier != 1 {
		panic(spell.ActionID.String() + " has non-default CastTimeMultiplier during finalize!")
	}
	if spell.CostMultiplier != 1 {
		panic(spell.ActionID.String() + " has non-default CostMultiplier during finalize!")
	}
	spell.initialBonusHitRating = spell.BonusHitRating
	spell.initialBonusCritRating = spell.BonusCritRating
	spell.initialBonusSpellPower = spell.BonusSpellPower
	spell.initialDamageMultiplier = spell.DamageMultiplier
	spell.initialDamageMultiplierAdditive = spell.DamageMultiplierAdditive
	spell.initialCritMultiplier = spell.CritMultiplier
	spell.initialThreatMultiplier = spell.ThreatMultiplier

	if len(spell.splitSpellMetrics) > 1 && spell.ActionID.Tag != 0 {
		panic(spell.ActionID.String() + " has split metrics and a non-zero tag, can only have one!")
	}
	for i := range spell.splitSpellMetrics {
		spell.splitSpellMetrics[i] = make([]SpellMetrics, len(spell.Unit.Env.AllUnits))
	}
	spell.SpellMetrics = spell.splitSpellMetrics[0]
}

func (spell *Spell) reset(_ *Simulation) {
	for i := range spell.splitSpellMetrics {
		for j := range spell.SpellMetrics {
			spell.splitSpellMetrics[i][j] = SpellMetrics{}
		}
	}
	spell.casts = 0

	// Reset dynamic effects.
	spell.BonusHitRating = spell.initialBonusHitRating
	spell.BonusCritRating = spell.initialBonusCritRating
	spell.BonusSpellPower = spell.initialBonusSpellPower
	spell.CastTimeMultiplier = 1
	spell.CostMultiplier = 1
	spell.DamageMultiplier = spell.initialDamageMultiplier
	spell.DamageMultiplierAdditive = spell.initialDamageMultiplierAdditive
	spell.CritMultiplier = spell.initialCritMultiplier
	spell.ThreatMultiplier = spell.initialThreatMultiplier
}

func (spell *Spell) SetMetricsSplit(splitIdx int32) {
	spell.SpellMetrics = spell.splitSpellMetrics[splitIdx]
	spell.ActionID.Tag = splitIdx
}

func (spell *Spell) doneIteration() {
	if spell.Flags.Matches(SpellFlagNoMetrics) {
		return
	}

	if len(spell.splitSpellMetrics) == 1 {
		spell.Unit.Metrics.addSpellMetrics(spell, spell.ActionID, spell.SpellMetrics)
	} else {
		for i, spellMetrics := range spell.splitSpellMetrics {
			spell.Unit.Metrics.addSpellMetrics(spell, spell.ActionID.WithTag(int32(i)), spellMetrics)
		}
	}
}

func (spell *Spell) HealthMetrics(target *Unit) *ResourceMetrics {
	if spell.healthMetrics == nil {
		spell.healthMetrics = make([]*ResourceMetrics, len(spell.Unit.AttackTables))
	}
	if spell.healthMetrics[target.UnitIndex] == nil {
		spell.healthMetrics[target.UnitIndex] = target.NewHealthMetrics(spell.ActionID)
	}
	return spell.healthMetrics[target.UnitIndex]
}

func (spell *Spell) ReadyAt() time.Duration {
	return BothTimersReadyAt(spell.CD.Timer, spell.SharedCD.Timer)
}

func (spell *Spell) IsReady(sim *Simulation) bool {
	if spell == nil {
		return false
	}
	return BothTimersReady(spell.CD.Timer, spell.SharedCD.Timer, sim)
}

func (spell *Spell) TimeToReady(sim *Simulation) time.Duration {
	return MaxTimeToReady(spell.CD.Timer, spell.SharedCD.Timer, sim)
}

// Returns whether a call to Cast() would be successful, without actually
// doing a cast.
func (spell *Spell) CanCast(sim *Simulation, target *Unit) bool {
	if spell == nil {
		return false
	}

	if spell.ExtraCastCondition != nil && !spell.ExtraCastCondition(sim, target) {
		//if sim.Log != nil {
		//	sim.Log("Cant cast because of extra condition")
		//}
		return false
	}

	// While casting or channeling, no other action is possible
	if spell.Unit.Hardcast.Expires > sim.CurrentTime {
		//if sim.Log != nil {
		//	sim.Log("Cant cast because already casting/channeling")
		//}
		return false
	}

	if spell.DefaultCast.GCD > 0 && !spell.Unit.GCD.IsReady(sim) {
		//if sim.Log != nil {
		//	sim.Log("Cant cast because of GCD")
		//}
		return false
	}

	if !BothTimersReady(spell.CD.Timer, spell.SharedCD.Timer, sim) {
		//if sim.Log != nil {
		//	sim.Log("Cant cast because of CDs")
		//}
		return false
	}

	if spell.Cost != nil {
		// temp hack
		spell.CurCast.Cost = spell.DefaultCast.Cost
		if !spell.Cost.MeetsRequirement(sim, spell) {
			//if sim.Log != nil {
			//	sim.Log("Cant cast because of resource cost")
			//}
			return false
		}
	}

	return true
}

func (spell *Spell) Cast(sim *Simulation, target *Unit) bool {
	if target == nil {
		target = spell.Unit.CurrentTarget
	}
	return spell.castFn(sim, target)
}

// Skips the actual cast and applies spell effects immediately.
func (spell *Spell) SkipCastAndApplyEffects(sim *Simulation, target *Unit) {
	if sim.Log != nil && !spell.Flags.Matches(SpellFlagNoLogs) {
		spell.Unit.Log(sim, "Casting %s (Cost = %0.03f, Cast Time = %s)",
			spell.ActionID, spell.DefaultCast.Cost, time.Duration(0))
		spell.Unit.Log(sim, "Completed cast %s", spell.ActionID)
	}
	spell.applyEffects(sim, target)
}

func (spell *Spell) applyEffects(sim *Simulation, target *Unit) {
	spell.SpellMetrics[target.UnitIndex].Casts++
	spell.casts++

	spell.ApplyEffects(sim, target, spell)
}

func (spell *Spell) ApplyAOEThreatIgnoreMultipliers(threatAmount float64) {
	numTargets := spell.Unit.Env.GetNumTargets()
	for i := int32(0); i < numTargets; i++ {
		spell.SpellMetrics[i].TotalThreat += threatAmount
	}
}
func (spell *Spell) ApplyAOEThreat(threatAmount float64) {
	spell.ApplyAOEThreatIgnoreMultipliers(threatAmount * spell.Unit.PseudoStats.ThreatMultiplier)
}

func (spell *Spell) finalizeExpectedDamage(result *SpellResult) {
	if !spell.SpellSchool.Matches(SpellSchoolPhysical) && !spell.Flags.Matches(SpellFlagIgnoreResists) && spell.canBeResisted(result.Target) {
		result.Damage /= result.ResistanceMultiplier
		result.Damage *= AverageMagicPartialResistMultiplier
		result.ResistanceMultiplier = AverageMagicPartialResistMultiplier
	}
	result.inUse = false
}
func (spell *Spell) ExpectedInitialDamage(sim *Simulation, target *Unit) float64 {
	result := spell.expectedInitialDamageInternal(sim, target, spell, false)
	spell.finalizeExpectedDamage(result)
	return result.Damage
}
func (spell *Spell) ExpectedTickDamage(sim *Simulation, target *Unit) float64 {
	result := spell.expectedTickDamageInternal(sim, target, spell, false)
	spell.finalizeExpectedDamage(result)
	return result.Damage
}
func (spell *Spell) ExpectedTickDamageFromCurrentSnapshot(sim *Simulation, target *Unit) float64 {
	result := spell.expectedTickDamageInternal(sim, target, spell, true)
	spell.finalizeExpectedDamage(result)
	return result.Damage
}

// EffectiveCastTime is how long the spell ties the unit up: its cast or its GCD, whichever is longer.
// Neither is rounded to the server tick, which only the cast itself knows how to do (it needs the
// time the cast starts).
func (spell *Spell) EffectiveCastTime() time.Duration {
	return max(spell.timing.gcd(spell.Unit, spell.DefaultCast.GCD), spell.CastTime())
}

// Time until the cast is finished (ignoring GCD). It leaves out the rounding up to the server tick
// that makeCastFunc does, which needs the time the cast starts.
func (spell *Spell) CastTime() time.Duration {
	return spell.castTimeFn(spell)
}

// TravelTime is Spell::AddUnitTarget's missile delay: at least 5 yards, in whole ms.
func (spell *Spell) TravelTime() time.Duration {
	if spell.MissileSpeed == 0 {
		return 0
	}
	distance := max(spell.Unit.DistanceFromTarget, 5)
	return time.Duration(math.Floor(distance/spell.MissileSpeed*1000)) * time.Millisecond
}

// Handles computing the cost of spells and checking whether the Unit
// meets them.
type SpellCost interface {
	// Whether the Unit associated with the spell meets the resource cost
	// requirements to cast the spell.
	MeetsRequirement(*Simulation, *Spell) bool

	// Returns a message for when the cast fails due to lack of resources.
	CostFailureReason(*Simulation, *Spell) string

	// Subtracts the resources used from a cast from the Unit.
	SpendCost(*Simulation, *Spell)

	// Space for handling refund mechanics. Not all spells provide refunds.
	IssueRefund(*Simulation, *Spell)
}

func (spell *Spell) IssueRefund(sim *Simulation) {
	spell.Cost.IssueRefund(sim, spell)
}

// ServerSpell is the spell's server data, looked up by SpellID when it was registered. Nil for a spell
// with no entry, one that opts out with SpellFlagNoServerData, or one a ServerSpellID entry covers.
func (spell *Spell) ServerSpell() *serverdata.Spell {
	if spell.Flags.Matches(SpellFlagNoServerData) {
		return nil
	}
	return spell.serverSpell
}

// ServerConflicts lists what the spell declared that its server data rules out, and the server flags an
// entry turned down.
func (spell *Spell) ServerConflicts() []ServerConflict {
	return spell.serverConflicts
}

// ServerField is a value RegisterSpell checks against the spell's server data.
type ServerField uint8

const (
	ServerCastTime          ServerField = iota + 1 // DefaultCast.CastTime against CastMs
	ServerGCD                                      // DefaultCast.GCD against GCDMs, 0 outside category 133
	ServerCD                                       // CD.Duration against the spell's own cooldown
	ServerSharedCD                                 // SharedCD.Duration against its category's cooldown
	ServerBinary                                   // SpellFlagBinary
	ServerNoActiveDefense                          // SpellFlagNoActiveDefense
	ServerCompletelyBlocked                        // SpellFlagCompletelyBlocked
	ServerChanneled                                // SpellFlagChanneled
	// The SpellID is another spell on the server (Sim is the id, Server the right one), so none of its
	// data applies. Only an entry sets it, with KeepSim.
	ServerSpellID
)

var serverFieldNames = [...]string{
	ServerCastTime:          "CastTime",
	ServerGCD:               "GCD",
	ServerCD:                "CD",
	ServerSharedCD:          "SharedCD",
	ServerBinary:            "Binary",
	ServerNoActiveDefense:   "NoActiveDefense",
	ServerCompletelyBlocked: "CompletelyBlocked",
	ServerChanneled:         "Channeled",
	ServerSpellID:           "SpellID",
}

func (f ServerField) String() string {
	if int(f) < len(serverFieldNames) && serverFieldNames[f] != "" {
		return serverFieldNames[f]
	}
	return fmt.Sprintf("ServerField(%d)", f)
}

// ServerConflict is a value a spell declares that its server data rules out, or a server flag an entry
// turns down. Timings are in ms, flags 0 or 1. A timing talents, glyphs, set bonuses or items can reach
// isn't one.
type ServerConflict struct {
	Spell  ActionID
	Field  ServerField
	Sim    int64
	Server int64

	// the entry that covers it; without one, the server's value replaced the sim's
	Allowed *ServerConflictAllowance
}

func (c ServerConflict) String() string {
	return fmt.Sprintf("%s %s: sim %d, server %d", c.Spell, c.Field, c.Sim, c.Server)
}

// ServerConflictAllowance acknowledges one conflict. With KeepSim the spell keeps its own value, since it
// models what the spell's server data can't show: a pet's AI, how often a raid member casts an external
// buff, an item's cooldown, the triggered spell behind a dummy cast. Without it the server's value
// applies, and the entry stands for a declaration its class still has to fix.
type ServerConflictAllowance struct {
	Spell   ActionID
	Field   ServerField
	Sim     int64
	Server  int64
	KeepSim bool
	Why     string
}

type serverConflictKey struct {
	spell ActionID
	field ServerField
}

var serverAllowances = struct {
	sync.RWMutex
	byKey map[serverConflictKey]*ServerConflictAllowance
}{byKey: map[serverConflictKey]*ServerConflictAllowance{}}

// AllowServerConflicts registers entries from an init function. An entry covers its spell and field
// whatever the values are, so a build the presets don't show still keeps what the entry decides.
func AllowServerConflicts(entries ...ServerConflictAllowance) {
	serverAllowances.Lock()
	defer serverAllowances.Unlock()
	for i := range entries {
		e := &entries[i]
		key := serverConflictKey{e.Spell, e.Field}
		if _, ok := serverAllowances.byKey[key]; ok {
			panic(fmt.Sprintf("two server conflict entries for %s %s", e.Spell, e.Field))
		}
		serverAllowances.byKey[key] = e
	}
}

// ServerConflictAllowances lists every registered entry, sorted by spell and field.
func ServerConflictAllowances() []*ServerConflictAllowance {
	serverAllowances.RLock()
	defer serverAllowances.RUnlock()
	all := make([]*ServerConflictAllowance, 0, len(serverAllowances.byKey))
	for _, e := range serverAllowances.byKey {
		all = append(all, e)
	}
	sort.Slice(all, func(i, j int) bool {
		a, b := all[i], all[j]
		if a.Spell != b.Spell {
			return a.Spell.String() < b.Spell.String()
		}
		return a.Field < b.Field
	})
	return all
}

// findServerAllowance falls back to the untagged spell's entry, since tags often count raid slots.
func findServerAllowance(spell ActionID, field ServerField) *ServerConflictAllowance {
	serverAllowances.RLock()
	defer serverAllowances.RUnlock()
	if e, ok := serverAllowances.byKey[serverConflictKey{spell, field}]; ok {
		return e
	}
	spell.Tag = 0
	return serverAllowances.byKey[serverConflictKey{spell, field}]
}

// SPELL_ATTR0_CU_DIRECT_DAMAGE, SPELL_ATTR4_NO_CAST_LOG and SPELL_ATTR7_NO_ATTACK_DODGE/PARRY (SpellInfo.h,
// SharedDefines.h)
const (
	attrCuDirectDamage = 0x00000100
	attr4NoCastLog     = 0x00000001
	attr7NoAttackDodge = 0x00800000
	attr7NoAttackParry = 0x01000000
)

// the StartRecoveryCategory nearly every spell with a GCD shares
const gcdCategoryShared = 133

// applyServerData swaps what the spell declares for its server data: the flags its hit and resist rolls
// read, and for a spell the sim casts itself, its cast time, GCD and cooldowns.
func (spell *Spell) applyServerData(cast *CastConfig) {
	if spell.ActionID.SpellID == 0 || spell.Flags.Matches(SpellFlagNoServerData) {
		return
	}
	s := serverdata.SpellByID(spell.ActionID.SpellID)
	if s == nil {
		return
	}
	if e := findServerAllowance(spell.ActionID, ServerSpellID); e != nil && e.KeepSim {
		spell.serverConflicts = append(spell.serverConflicts, ServerConflict{
			Spell: spell.ActionID, Field: ServerSpellID, Sim: int64(spell.ActionID.SpellID), Server: e.Server, Allowed: e,
		})
		return
	}
	spell.serverSpell = s

	spell.syncServerFlag(ServerBinary, SpellFlagBinary, s.Flags&serverdata.FlagBinary != 0)
	spell.syncServerFlag(ServerNoActiveDefense, SpellFlagNoActiveDefense, s.Flags&serverdata.FlagNoActiveDefense != 0)
	// MeleeSpellHitResult only puts the block in the table without CU_DIRECT_DAMAGE
	spell.syncServerFlag(ServerCompletelyBlocked, SpellFlagCompletelyBlocked,
		s.Flags&serverdata.FlagCompletelyBlocked != 0 && s.AttributesCu&attrCuDirectDamage == 0)
	spell.syncServerFlag(ServerChanneled, SpellFlagChanneled, s.Flags&serverdata.FlagChanneled != 0)

	// Auras grant these too (Surprise Attacks), so the attributes only ever add them.
	if s.Flags&serverdata.FlagAlwaysHit != 0 {
		spell.Flags |= SpellFlagAlwaysHit
	}
	if s.Attributes[7]&attr7NoAttackDodge != 0 {
		spell.Flags |= SpellFlagCannotBeDodged
	}
	if s.Attributes[7]&attr7NoAttackParry != 0 {
		spell.Flags |= SpellFlagCannotBeParried
	}
	// CalcAbsorbResist never partially resists these. Not on physical spells: IgnoreResists would skip armor too.
	if s.Attributes[4]&attr4NoCastLog != 0 && !spell.SpellSchool.Matches(SpellSchoolPhysical) {
		spell.Flags |= SpellFlagIgnoreResists
	}

	// No cast, no GCD and no cooldown: the sim triggers it, and a triggered cast skips all three.
	var emptyCast Cast
	if spell.DefaultCast == emptyCast && cast.CD.Timer == nil && cast.SharedCD.Timer == nil {
		return
	}
	// Creatures get no GCD (Spell::TriggerGlobalCooldown), and their scripts time every cast, which the
	// encounter AIs model.
	if spell.Unit.Type == EnemyUnit {
		return
	}

	lo, hi := s.CastRange()
	spell.syncServerTiming(ServerCastTime, &spell.DefaultCast.CastTime, s.CastMs, lo, hi)
	// GlobalCooldownMgr keys the GCD by StartRecoveryCategory and the unit's one GCD is 133's. Any other
	// category only holds back its own spells (Spirit Strike's GCD has none), so counts as no GCD.
	gcdMs := int32(0)
	lo, hi = 0, 0
	if s.GCDCategory == gcdCategoryShared {
		gcdMs = s.GCDMs
		lo, hi = s.GCDRange()
	}
	spell.syncServerTiming(ServerGCD, &spell.DefaultCast.GCD, gcdMs, lo, hi)

	if own := s.OwnCooldownMs(); cast.CD.Timer != nil || own > 0 {
		lo, hi = s.CooldownRange(own, s.CooldownMs <= 0)
		if spell.syncServerTiming(ServerCD, &spell.CD.Duration, own, lo, hi) && spell.CD.Timer == nil {
			spell.CD.Timer = spell.Unit.NewTimer()
			cast.CD = spell.CD
		}
	}
	if cast.SharedCD.Timer != nil {
		lo, hi = s.CooldownRange(s.CategoryCooldownMs, true)
		spell.syncServerTiming(ServerSharedCD, &spell.SharedCD.Duration, s.CategoryCooldownMs, lo, hi)
	}
}

// syncServerFlag takes the server's flag. A flag the spell doesn't set is nothing it declared, so only
// one it sets and the server lacks is a conflict, unless a KeepSim entry turns the server's flag down:
// a dummy cast whose hit the server rolls on the triggered spell that does the damage.
func (spell *Spell) syncServerFlag(field ServerField, flag SpellFlag, server bool) {
	declared := spell.Flags.Matches(flag)
	if declared == server {
		return
	}
	if !declared {
		if e := findServerAllowance(spell.ActionID, field); e != nil && e.KeepSim {
			spell.serverConflicts = append(spell.serverConflicts, ServerConflict{
				Spell: spell.ActionID, Field: field, Sim: 0, Server: 1, Allowed: e,
			})
			return
		}
		spell.Flags |= flag
		return
	}
	if spell.recordServerConflict(field, 1, 0) {
		spell.Flags &^= flag
	}
}

// syncServerTiming takes the server's value when the declared one is outside what the modifiers can
// reach, and reports whether it did.
func (spell *Spell) syncServerTiming(field ServerField, value *time.Duration, serverMs, lo, hi int32) bool {
	ms := float64(*value) / float64(time.Millisecond)
	// 1 ms for the server's float math
	if ms >= float64(lo)-1 && ms <= float64(hi)+1 {
		return false
	}
	if !spell.recordServerConflict(field, int64(math.Round(ms)), int64(serverMs)) {
		return false
	}
	*value = time.Duration(serverMs) * time.Millisecond
	return true
}

// recordServerConflict reports whether the server's value applies.
func (spell *Spell) recordServerConflict(field ServerField, sim, server int64) bool {
	allowed := findServerAllowance(spell.ActionID, field)
	spell.serverConflicts = append(spell.serverConflicts, ServerConflict{
		Spell: spell.ActionID, Field: field, Sim: sim, Server: server, Allowed: allowed,
	})
	return allowed == nil || !allowed.KeepSim
}
