package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/wowsims/wotlk/sim/core/serverdata"
)

const header = `// Code generated by tools/acore/gen_serverdata from assets/db_inputs/acore/spelldump.jsonl and the live
// world DB. DO NOT EDIT.

package serverdata

`

var dmgClassNames = map[serverdata.DmgClass]string{
	serverdata.DmgClassNone:   "DmgClassNone",
	serverdata.DmgClassMagic:  "DmgClassMagic",
	serverdata.DmgClassMelee:  "DmgClassMelee",
	serverdata.DmgClassRanged: "DmgClassRanged",
}

var flagNames = []struct {
	flag serverdata.Flags
	name string
}{
	{serverdata.FlagUsesRangedSlot, "FlagUsesRangedSlot"},
	{serverdata.FlagBinary, "FlagBinary"},
	{serverdata.FlagNoActiveDefense, "FlagNoActiveDefense"},
	{serverdata.FlagAlwaysHit, "FlagAlwaysHit"},
	{serverdata.FlagCompletelyBlocked, "FlagCompletelyBlocked"},
	{serverdata.FlagResetsAutoAttack, "FlagResetsAutoAttack"},
	{serverdata.FlagHasteAffectsPeriodic, "FlagHasteAffectsPeriodic"},
	{serverdata.FlagHasteGCD, "FlagHasteGCD"},
	{serverdata.FlagChanneled, "FlagChanneled"},
	{serverdata.FlagAutoRepeat, "FlagAutoRepeat"},
	{serverdata.FlagPassive, "FlagPassive"},
	{serverdata.FlagPositive, "FlagPositive"},
}

// fields builds a keyed composite literal body, leaving out zero values.
type fields []string

func (f *fields) add(name, value string) { *f = append(*f, name+": "+value) }

func (f *fields) int(name string, v int32) {
	if v != 0 {
		f.add(name, strconv.Itoa(int(v)))
	}
}

func (f *fields) hex(name string, v uint32) {
	if v != 0 {
		f.add(name, hex(v))
	}
}

func (f *fields) float(name string, v float32) {
	if v != 0 {
		f.add(name, float(v))
	}
}

// masks writes a mask array without its trailing zeros, or nothing when it's all zero.
func (f *fields) masks(name string, vs []uint32) {
	n := len(vs)
	for n > 0 && vs[n-1] == 0 {
		n--
	}
	if n == 0 {
		return
	}
	parts := make([]string, n)
	for i, v := range vs[:n] {
		parts[i] = hex(v)
	}
	f.add(name, fmt.Sprintf("[%d]uint32{%s}", len(vs), strings.Join(parts, ", ")))
}

func (f fields) String() string { return strings.Join(f, ", ") }

func hex(v uint32) string {
	if v == 0 {
		return "0"
	}
	return fmt.Sprintf("%#x", v)
}

func float(v float32) string { return strconv.FormatFloat(float64(v), 'g', -1, 32) }

func comment(name string) string {
	return strings.NewReplacer("\n", " ", "\r", " ").Replace(name)
}

func renderFlags(f serverdata.Flags) (string, error) {
	var names []string
	for _, n := range flagNames {
		if f&n.flag != 0 {
			names = append(names, n.name)
			f &^= n.flag
		}
	}
	if f != 0 {
		return "", fmt.Errorf("flags %#x have no name in flagNames", uint32(f))
	}
	return strings.Join(names, " | "), nil
}

func renderSpells(spells []namedSpell) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("var spells = []Spell{\n")
	for _, s := range spells {
		fmt.Fprintf(&b, "\t// %s\n\t{\n", comment(s.name))

		var id fields
		id.int("ID", s.ID)
		id.int("Family", s.Family)
		id.masks("FamilyFlags", s.FamilyFlags[:])
		id.int("SchoolMask", int32(s.SchoolMask))
		if s.DmgClass != serverdata.DmgClassNone {
			id.add("DmgClass", dmgClassNames[s.DmgClass])
		}
		if s.Flags != 0 {
			flags, err := renderFlags(s.Flags)
			if err != nil {
				return nil, fmt.Errorf("spell %d: %w", s.ID, err)
			}
			id.add("Flags", flags)
		}

		var attrs fields
		attrs.masks("Attributes", s.Attributes[:])
		attrs.hex("AttributesCu", s.AttributesCu)

		var timing fields
		timing.int("CastMs", s.CastMs)
		timing.int("BaseCastMs", s.BaseCastMs)
		timing.int("GCDMs", s.GCDMs)
		timing.int("GCDCategory", s.GCDCategory)
		timing.int("CooldownMs", s.CooldownMs)
		timing.int("CategoryCooldownMs", s.CategoryCooldownMs)
		timing.int("Category", s.Category)
		timing.int("DurationMs", s.DurationMs)
		timing.int("MaxDurationMs", s.MaxDurationMs)
		timing.int("StackAmount", s.StackAmount)

		var other fields
		other.hex("ProcFlags", s.ProcFlags)
		other.int("ProcChance", s.ProcChance)
		other.int("ProcCharges", s.ProcCharges)
		other.int("PowerType", s.PowerType)
		other.int("ManaCost", s.ManaCost)
		other.int("ManaCostPct", s.ManaCostPct)
		other.int("RuneCostID", s.RuneCostID)
		other.float("Speed", s.Speed)
		other.int("MaxTargets", s.MaxTargets)

		for _, line := range []fields{id, attrs, timing, other} {
			if len(line) > 0 {
				fmt.Fprintf(&b, "\t\t%s,\n", line)
			}
		}

		n := len(s.Effects)
		for n > 0 && s.Effects[n-1] == (serverdata.Effect{}) {
			n--
		}
		if n > 0 {
			b.WriteString("\t\tEffects: [3]Effect{\n")
			for _, e := range s.Effects[:n] {
				fmt.Fprintf(&b, "\t\t\t{%s},\n", renderEffect(e))
			}
			b.WriteString("\t\t},\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

func renderEffect(e serverdata.Effect) string {
	var f fields
	f.int("Effect", e.Effect)
	f.int("Aura", e.Aura)
	f.int("AmplitudeMs", e.AmplitudeMs)
	f.int("BasePoints", e.BasePoints)
	f.int("DieSides", e.DieSides)
	f.float("PointsPerLevel", e.PointsPerLevel)
	f.float("PointsPerComboPoint", e.PointsPerComboPoint)
	f.float("ValueMultiplier", e.ValueMultiplier)
	f.float("DamageMultiplier", e.DamageMultiplier)
	f.float("BonusMultiplier", e.BonusMultiplier)
	f.int("MiscValue", e.MiscValue)
	f.int("MiscValueB", e.MiscValueB)
	f.int("TriggerSpell", e.TriggerSpell)
	f.int("ChainTargets", e.ChainTargets)
	f.masks("ClassMask", e.ClassMask[:])
	return f.String()
}

func renderProcs(procs []serverdata.Proc, names map[int32]string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("var procs = []Proc{\n")
	for _, p := range procs {
		var f fields
		f.int("SpellID", p.SpellID)
		f.int("Row", p.Row)
		f.int("SchoolMask", int32(p.SchoolMask))
		f.int("SpellFamilyName", p.SpellFamilyName)
		f.masks("SpellFamilyMask", p.SpellFamilyMask[:])
		f.hex("ProcFlags", p.ProcFlags)
		f.hex("SpellTypeMask", p.SpellTypeMask)
		f.hex("SpellPhaseMask", p.SpellPhaseMask)
		f.hex("HitMask", p.HitMask)
		f.hex("AttributesMask", p.AttributesMask)
		f.hex("DisableEffectsMask", p.DisableEffectsMask)
		f.float("ProcsPerMinute", p.ProcsPerMinute)
		f.float("Chance", p.Chance)
		f.int("CooldownMs", p.CooldownMs)
		f.int("Charges", p.Charges)
		fmt.Fprintf(&b, "\t{%s}, // %s\n", f, comment(names[p.SpellID]))
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

func renderBonuses(bonuses []serverdata.Bonus, names map[int32]string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("var bonuses = []Bonus{\n")
	for _, bonus := range bonuses {
		var f fields
		f.int("SpellID", bonus.SpellID)
		f.int("Row", bonus.Row)
		f.float("Direct", bonus.Direct)
		f.float("Dot", bonus.Dot)
		f.float("AP", bonus.AP)
		f.float("APDot", bonus.APDot)
		fmt.Fprintf(&b, "\t{%s}, // %s\n", f, comment(names[bonus.SpellID]))
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

func renderEnchantProcs(procs []serverdata.EnchantProc) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("var enchantProcs = []EnchantProc{\n")
	for _, e := range procs {
		var f fields
		f.int("EnchantID", e.EnchantID)
		f.int("CustomChance", e.CustomChance)
		f.float("PPM", e.PPM)
		f.hex("ProcEx", e.ProcEx)
		f.hex("AttributeMask", e.AttributeMask)
		fmt.Fprintf(&b, "\t{%s},\n", f)
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}
