import { RESILIENCE_RATING_PER_CRIT_REDUCTION_CHANCE } from './ratings_auto_gen.js';

export * from './ratings_auto_gen.js';

export const CHARACTER_LEVEL = 80;
export const MAX_TALENT_POINTS = CHARACTER_LEVEL - 9;
export const BOSS_LEVEL = CHARACTER_LEVEL + 3;

export const MISS_DODGE_PARRY_BLOCK_CRIT_CHANCE_PER_DEFENSE = 0.04;
export const RESILIENCE_RATING_PER_CRIT_DAMAGE_REDUCTION_PERCENT = RESILIENCE_RATING_PER_CRIT_REDUCTION_CHANCE / 2.2;
