// Code generated by tools/acore/gen_basestats. DO NOT EDIT.

import { Class } from '../proto/common.js';

// Rating for 1%, or for one point of defense or expertise, at level 80.
export const EXPERTISE_PER_QUARTER_PERCENT_REDUCTION = 8.197496;
export const HASTE_RATING_PER_HASTE_PERCENT = 32.78999;
export const MELEE_CRIT_RATING_PER_CRIT_CHANCE = 45.905987;
export const SPELL_CRIT_RATING_PER_CRIT_CHANCE = 45.905987;
export const MELEE_HIT_RATING_PER_HIT_CHANCE = 32.78999;
export const SPELL_HIT_RATING_PER_HIT_CHANCE = 26.231993;
export const DEFENSE_RATING_PER_DEFENSE = 4.918498;
export const DODGE_RATING_PER_DODGE_CHANCE = 45.250187;
export const PARRY_RATING_PER_PARRY_CHANCE = 45.250187;
export const BLOCK_RATING_PER_BLOCK_CHANCE = 16.394995;
export const RESILIENCE_RATING_PER_CRIT_REDUCTION_CHANCE = 94.271225;

export const MELEE_HASTE_RATING_PER_HASTE_PERCENT_BY_CLASS: Record<Class, number> = {
	[Class.ClassUnknown]: 32.78999,
	[Class.ClassWarrior]: 32.78999,
	[Class.ClassPaladin]: 32.78999 / 1.3,
	[Class.ClassHunter]: 32.78999,
	[Class.ClassRogue]: 32.78999,
	[Class.ClassPriest]: 32.78999,
	[Class.ClassDeathknight]: 32.78999 / 1.3,
	[Class.ClassShaman]: 32.78999 / 1.3,
	[Class.ClassMage]: 32.78999,
	[Class.ClassWarlock]: 32.78999,
	[Class.ClassDruid]: 32.78999 / 1.3,
};

export const ARMOR_PEN_RATING_PER_PERCENT_BY_CLASS: Record<Class, number> = {
	[Class.ClassUnknown]: 15.3953,
	[Class.ClassWarrior]: 15.3953 / 1.1,
	[Class.ClassPaladin]: 15.3953 / 1.1,
	[Class.ClassHunter]: 15.3953 / 1.1,
	[Class.ClassRogue]: 15.3953 / 1.1,
	[Class.ClassPriest]: 15.3953 / 1.1,
	[Class.ClassDeathknight]: 15.3953 / 1.1,
	[Class.ClassShaman]: 15.3953 / 1.1,
	[Class.ClassMage]: 15.3953 / 1.1,
	[Class.ClassWarlock]: 15.3953 / 1.1,
	[Class.ClassDruid]: 15.3953 / 1.1,
};
