// Code generated by tools/acore/gen_server_defaults. DO NOT EDIT.

import { ServerSettings } from '../proto/common.js';

// The live AzerothCore config: worldserver.conf.dist, the mod-spell-tweaks, mod-dungeon-scale and
// mod-reforging conf.dist files, and configurationOverrides/{ServerPerformance,SpellTweaks,DungeonScale}.env.
// A dungeon scale size set only holds what the config sets; the rest falls back to raid or raidHeroic.
export const LIVE_SERVER_DEFAULTS = ServerSettings.create({
	mapUpdateIntervalMs: 100,
	spellTweaks: {
		enable: true,
		exoticPetDamagePct: 0,
		hunterPetHaste: true,
		hunterPetArmorPen: true,
		dkGhoulArmorPen: true,
		feralSpiritHaste: true,
		diseaseHaste: true,
		deadlyPoisonMurder: true,
		ruptureWeaponExpertise: true,
		rendTrauma: true,
		balanceDotScaling: true,
		titansGripNoDamagePenalty: true,
		omenClarityFaerieFire: true,
	},
	dungeonScale: {
		raid: { global: 1, health: 1, armor: 1, damage: 1 },
		raidBoss: { global: 1, health: 1.2, armor: 1, damage: 1 },
		raidHeroic: { global: 1, health: 1, armor: 1, damage: 1 },
		raidHeroicBoss: { global: 1, health: 1.2, armor: 1, damage: 1 },
	},
	reforge: { enable: true, percentage: 40, statTypes: [6, 13, 14, 31, 32, 36, 37] },
});
