package main

import (
	"bytes"
	"cmp"
	"encoding/csv"
	"fmt"
	"log"
	"os"
	"slices"
	"strings"

	"github.com/wowsims/wotlk/sim/core/proto"
)

func writeCSV(name string, header []string, rows [][]string) {
	f, err := os.Create(outPath(name))
	check(err)
	defer f.Close()
	w := csv.NewWriter(f)
	check(w.Write(header))
	check(w.WriteAll(rows))
	log.Printf("%s: %d rows", name, len(rows))
}

func intsString(values []int32) string {
	var parts []string
	for _, v := range values {
		parts = append(parts, fmt.Sprint(v))
	}
	return strings.Join(parts, " ")
}

func (c *context) writeItemDiffs(diffs, notComparable []itemDiff) {
	var rows [][]string
	for _, d := range diffs {
		zone, difficulty := c.primarySource(d.sim)
		rows = append(rows, []string{
			fmt.Sprint(d.sim.Id), d.sim.Name, d.category(),
			fmt.Sprint(d.server.Item.Ilvl), fmt.Sprint(d.sim.Ilvl),
			zone, difficulty, d.diffString(),
			intsString(d.unmappedStats), strings.Join(d.moduleFiles, " "), c.simSourceString(d.sim),
		})
	}
	writeCSV("items_diff.csv", []string{"id", "name", "category", "server_ilvl", "sim_ilvl", "zone", "difficulty",
		"diffs (server -> sim)", "server_unmapped_stat_types", "module_files", "sim_sources"}, rows)

	rows = nil
	for _, d := range notComparable {
		rows = append(rows, []string{fmt.Sprint(d.sim.Id), d.sim.Name, d.server.NotComparable, d.diffString()})
	}
	writeCSV("items_not_comparable.csv", []string{"id", "name", "reason", "diffs (server -> sim)"}, rows)
}

func (c *context) writeMissingOnServer(items []*proto.UIItem) {
	var rows [][]string
	for _, item := range items {
		rows = append(rows, []string{fmt.Sprint(item.Id), item.Name, fmt.Sprint(item.Ilvl), c.simSourceString(item)})
	}
	writeCSV("items_missing_on_server.csv", []string{"id", "name", "sim_ilvl", "sim_sources"}, rows)
}

func writeObtainability(name string, header []string, items []obtainabilityRow, withDetail bool) {
	var rows [][]string
	for _, item := range items {
		row := []string{fmt.Sprint(item.id), item.name, fmt.Sprint(item.ilvl)}
		if withDetail {
			row = append(row, item.detail)
		}
		rows = append(rows, append(row, item.sources))
	}
	writeCSV(name, header, rows)
}

func writeEffects(name string, effects []effectRow) {
	var rows [][]string
	for _, e := range effects {
		rows = append(rows, []string{
			e.kind, fmt.Sprint(e.id), e.name, e.context, e.goVerdict, e.classicVerdict,
			idsString(e.chain), valuesString(e.serverValues),
			valuesString(e.notInGo), numbersString(e.goNumbers), formatLocations(e.goLocations),
			valuesString(e.notInClassic), numbersString(e.classicNumbers), e.serverDescription, e.classicText,
			strings.Join(e.moduleFiles, " "),
		})
	}
	writeCSV(name, []string{"kind", "id", "name", "context", "go_verdict", "classic_verdict", "spell_chain", "server_values",
		"server_values_not_in_go", "go_numbers", "go_locations",
		"server_values_not_in_classic", "classic_tooltip_numbers", "server_description", "classic_tooltip_text", "module_files"}, rows)
}

func writeSetIssues(issues []setRow) {
	var rows [][]string
	for _, issue := range issues {
		rows = append(rows, []string{issue.name, issue.issue, issue.detail})
	}
	writeCSV("sets_issues.csv", []string{"sim_set_name", "issue", "detail"}, rows)
}

func writeGemOrEnchantDiffs(name string, diffs []gemOrEnchantDiff) {
	var rows [][]string
	for _, d := range diffs {
		var parts []string
		for _, f := range d.diffs {
			parts = append(parts, fmt.Sprintf("%s: %s -> %s", f.field, f.server, f.sim))
		}
		rows = append(rows, []string{d.kind, fmt.Sprint(d.id), d.name, d.issue, strings.Join(parts, "; "), d.extra})
	}
	writeCSV(name, []string{"kind", "id", "name", "issue", "diffs (server -> sim)", "extra"}, rows)
}

type summaryInput struct {
	itemDiffs       []itemDiff
	missingOnServer []*proto.UIItem
	notComparable   []itemDiff
	unobtainable    []obtainabilityRow
	missingInSim    []obtainabilityRow
	effects         []effectRow
	setEffects      []effectRow
	setIssues       []setRow
	gemDiffs        []gemOrEnchantDiff
	enchantDiffs    []gemOrEnchantDiff
}

type countRow struct {
	key   string
	count int
}

func sortedCounts(counts map[string]int) []countRow {
	var rows []countRow
	for k, v := range counts {
		rows = append(rows, countRow{k, v})
	}
	slices.SortFunc(rows, func(a, b countRow) int {
		return cmp.Or(cmp.Compare(b.count, a.count), cmp.Compare(a.key, b.key))
	})
	return rows
}

func (c *context) writeSummary(in summaryInput) {
	var b bytes.Buffer
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("# AzerothCore vs sim item data: summary")
	p("")
	p("Generated by `go run ./tools/database/acdiff`. Diffs read server -> sim.")
	p("")
	p("## Items")
	p("")
	categories := map[string]int{}
	ilvl := 0
	for _, d := range in.itemDiffs {
		categories[d.category()]++
		if d.ilvlChanged() {
			ilvl++
		}
	}
	p("| | count |")
	p("|---|---|")
	p("| sim items | %d |", len(c.sim.Items))
	p("| missing on server | %d |", len(in.missingOnServer))
	p("| not comparable (random enchant / scaling) | %d |", len(in.notComparable))
	p("| with differences | %d |", len(in.itemDiffs))
	p("| ... classic (obtainable, not touched by module SQL) | %d |", categories["classic"])
	p("| ... module (obtainable, touched by module/custom SQL) | %d |", categories["module"])
	p("| ... unobtainable on server | %d |", categories["unobtainable"])
	p("| ... with ilvl changes (any category) | %d |", ilvl)
	p("")

	transitions := map[string]int{}
	byZone := map[string]int{}
	sameIlvlFields := map[string]int{}
	moduleFields := map[string]int{}
	unobtainableFields := map[string]int{}
	for _, d := range in.itemDiffs {
		switch d.category() {
		case "module":
			for _, f := range d.diffs {
				moduleFields[f.field]++
			}
			continue
		case "unobtainable":
			for _, f := range d.diffs {
				unobtainableFields[f.field]++
			}
			continue
		}
		if d.ilvlChanged() {
			transitions[fmt.Sprintf("%d -> %d", d.server.Item.Ilvl, d.sim.Ilvl)]++
			zone, difficulty := c.primarySource(d.sim)
			byZone[fmt.Sprintf("%s | %s | %d -> %d", zone, difficulty, d.server.Item.Ilvl, d.sim.Ilvl)]++
		} else {
			for _, f := range d.diffs {
				sameIlvlFields[f.field]++
			}
		}
	}

	p("### Ilvl changes, server -> sim (classic category)")
	p("")
	p("| server -> sim | items |")
	p("|---|---|")
	for _, r := range sortedCounts(transitions) {
		p("| %s | %d |", r.key, r.count)
	}
	p("")
	p("### Ilvl changes by sim source")
	p("")
	p("| zone | difficulty | server -> sim | items |")
	p("|---|---|---|---|")
	for _, r := range sortedCounts(byZone) {
		parts := strings.SplitN(r.key, " | ", 3)
		p("| %s | %s | %s | %d |", parts[0], parts[1], parts[2], r.count)
	}
	p("")
	fieldTable := func(title string, counts map[string]int) {
		p("### %s", title)
		p("")
		p("| field | items |")
		p("|---|---|")
		for _, r := range sortedCounts(counts) {
			p("| %s | %d |", r.key, r.count)
		}
		p("")
	}
	fieldTable("Differing fields on same-ilvl items (classic category)", sameIlvlFields)
	fieldTable("Differing fields (module category)", moduleFields)
	fieldTable("Differing fields (unobtainable category)", unobtainableFields)

	p("## Obtainability")
	p("")
	p("- sim items not obtainable on the server: %d (`items_unobtainable_on_server.csv`)", len(in.unobtainable))
	p("- obtainable rare+ ilvl 187+ server gear missing from the sim: %d (`items_missing_in_sim.csv`)", len(in.missingInSim))
	p("")

	writeEffectSummary := func(title string, rows []effectRow) {
		p("## %s", title)
		p("")
		verdicts := map[string]int{}
		for _, e := range rows {
			verdicts[fmt.Sprintf("%s | %s | %s", e.kind, e.goVerdict, e.classicVerdict)]++
		}
		p("| kind | sim Go vs server | Classic tooltip vs server | rows |")
		p("|---|---|---|---|")
		for _, r := range sortedCounts(verdicts) {
			parts := strings.SplitN(r.key, " | ", 3)
			p("| %s | %s | %s | %d |", parts[0], parts[1], parts[2], r.count)
		}
		p("")
	}
	writeEffectSummary("Item, gem and enchant effects (`effects_diff.csv`)", in.effects)
	writeEffectSummary("Set bonuses (`sets_diff.csv`)", in.setEffects)

	issues := map[string]int{}
	for _, issue := range in.setIssues {
		issues[issue.issue]++
	}
	p("Set issues (`sets_issues.csv`):")
	p("")
	for _, r := range sortedCounts(issues) {
		p("- %s: %d", r.key, r.count)
	}
	p("")

	p("## Gems and enchants")
	p("")
	gemOrEnchantCounts := map[string]int{}
	for _, d := range slices.Concat(in.gemDiffs, in.enchantDiffs) {
		gemOrEnchantCounts[d.kind+": "+d.issue]++
	}
	for _, r := range sortedCounts(gemOrEnchantCounts) {
		p("- %s: %d", r.key, r.count)
	}

	check(os.WriteFile(outPath("summary.md"), b.Bytes(), 0o644))
}
