package main

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/wowsims/wotlk/sim/core/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const header = "// Code generated by tools/acore/gen_server_defaults. DO NOT EDIT.\n"

const sources = "// The live AzerothCore config: worldserver.conf.dist, the mod-spell-tweaks, mod-dungeon-scale and\n" +
	"// mod-reforging conf.dist files, and configurationOverrides/{ServerPerformance,SpellTweaks,DungeonScale}.env.\n"

func renderGo(settings *proto.ServerSettings, f floors) ([]byte, error) {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	p("%s\n", header)
	p("%s\n", sources)
	p("package core\n\n")
	p("import (\n\t\"github.com/wowsims/wotlk/sim/core/proto\"\n\tgoogleProto \"google.golang.org/protobuf/proto\"\n)\n\n")

	p("// LiveServerDefaults is the live server's value for every ServerSettings field. A dungeon scale\n")
	p("// size set only holds what the config sets; the rest falls back to Raid or RaidHeroic.\n")
	p("func LiveServerDefaults() *proto.ServerSettings {\n\treturn ")
	if err := goMessage(&b, settings.ProtoReflect()); err != nil {
		return nil, err
	}
	p("\n}\n\n")

	p("// DungeonScale.MinHPModifier and DungeonScale.MinDamageModifier: the lowest a health or damage\n")
	p("// multiplier goes.\nconst (\n")
	p("\tDungeonScaleMinHealthModifier = %s\n", strconv.FormatFloat(float64(f.minHealth), 'g', -1, 32))
	p("\tDungeonScaleMinDamageModifier = %s\n)\n", strconv.FormatFloat(float64(f.minDamage), 'g', -1, 32))

	return format.Source([]byte(b.String()))
}

func renderTS(settings *proto.ServerSettings) ([]byte, error) {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	p("%s\n", header)
	p("import { ServerSettings } from '../proto/common.js';\n\n")
	p("%s", sources)
	p("// A dungeon scale size set only holds what the config sets; the rest falls back to raid or raidHeroic.\n")
	p("export const LIVE_SERVER_DEFAULTS = ServerSettings.create(")
	if err := tsMessage(&b, settings.ProtoReflect(), 0); err != nil {
		return nil, err
	}
	p(");\n")
	return []byte(b.String()), nil
}

// setFields lists a message's set fields in .proto order, so reruns print the same file.
func setFields(m protoreflect.Message) []protoreflect.FieldDescriptor {
	var out []protoreflect.FieldDescriptor
	fields := m.Descriptor().Fields()
	for i := 0; i < fields.Len(); i++ {
		if fd := fields.Get(i); m.Has(fd) {
			out = append(out, fd)
		}
	}
	return out
}

// A short message with only scalar fields prints on one line.
func isInline(fields []protoreflect.FieldDescriptor) bool {
	for _, fd := range fields {
		if fd.Kind() == protoreflect.MessageKind {
			return false
		}
	}
	return len(fields) <= 4
}

func goFieldName(fd protoreflect.FieldDescriptor) string {
	var b strings.Builder
	for _, part := range strings.Split(string(fd.Name()), "_") {
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

func goMessage(b *strings.Builder, m protoreflect.Message) error {
	fields := setFields(m)
	inline := isInline(fields)
	fmt.Fprintf(b, "&proto.%s{", m.Descriptor().Name())
	for i, fd := range fields {
		if inline {
			if i > 0 {
				b.WriteString(", ")
			}
		} else {
			b.WriteString("\n")
		}
		fmt.Fprintf(b, "%s: ", goFieldName(fd))
		if err := goValue(b, fd, m.Get(fd)); err != nil {
			return err
		}
		if !inline {
			b.WriteString(",")
		}
	}
	if !inline {
		b.WriteString("\n")
	}
	b.WriteString("}")
	return nil
}

func goValue(b *strings.Builder, fd protoreflect.FieldDescriptor, v protoreflect.Value) error {
	if fd.IsList() {
		if fd.Kind() != protoreflect.Int32Kind {
			return fmt.Errorf("%s: can't print a repeated %s", fd.FullName(), fd.Kind())
		}
		list := v.List()
		items := make([]string, list.Len())
		for i := range items {
			items[i] = strconv.FormatInt(list.Get(i).Int(), 10)
		}
		fmt.Fprintf(b, "[]int32{%s}", strings.Join(items, ", "))
		return nil
	}
	switch fd.Kind() {
	case protoreflect.BoolKind:
		fmt.Fprintf(b, "googleProto.Bool(%t)", v.Bool())
	case protoreflect.Int32Kind:
		fmt.Fprintf(b, "googleProto.Int32(%d)", v.Int())
	case protoreflect.DoubleKind:
		fmt.Fprintf(b, "googleProto.Float64(%s)", strconv.FormatFloat(v.Float(), 'g', -1, 64))
	case protoreflect.MessageKind:
		return goMessage(b, v.Message())
	default:
		return fmt.Errorf("%s: can't print a %s", fd.FullName(), fd.Kind())
	}
	return nil
}

func tsMessage(b *strings.Builder, m protoreflect.Message, depth int) error {
	fields := setFields(m)
	if isInline(fields) {
		parts := make([]string, len(fields))
		for i, fd := range fields {
			value, err := tsValue(fd, m.Get(fd), depth)
			if err != nil {
				return err
			}
			parts[i] = fd.JSONName() + ": " + value
		}
		fmt.Fprintf(b, "{ %s }", strings.Join(parts, ", "))
		return nil
	}

	indent := strings.Repeat("\t", depth+1)
	b.WriteString("{\n")
	for _, fd := range fields {
		value, err := tsValue(fd, m.Get(fd), depth+1)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "%s%s: %s,\n", indent, fd.JSONName(), value)
	}
	b.WriteString(strings.Repeat("\t", depth) + "}")
	return nil
}

func tsValue(fd protoreflect.FieldDescriptor, v protoreflect.Value, depth int) (string, error) {
	if fd.IsList() {
		if fd.Kind() != protoreflect.Int32Kind {
			return "", fmt.Errorf("%s: can't print a repeated %s", fd.FullName(), fd.Kind())
		}
		list := v.List()
		items := make([]string, list.Len())
		for i := range items {
			items[i] = strconv.FormatInt(list.Get(i).Int(), 10)
		}
		return "[" + strings.Join(items, ", ") + "]", nil
	}
	switch fd.Kind() {
	case protoreflect.BoolKind:
		return strconv.FormatBool(v.Bool()), nil
	case protoreflect.Int32Kind:
		return strconv.FormatInt(v.Int(), 10), nil
	case protoreflect.DoubleKind:
		return strconv.FormatFloat(v.Float(), 'g', -1, 64), nil
	case protoreflect.MessageKind:
		var b strings.Builder
		err := tsMessage(&b, v.Message(), depth)
		return b.String(), err
	}
	return "", fmt.Errorf("%s: can't print a %s", fd.FullName(), fd.Kind())
}
