package main

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

const header = "// Code generated by tools/acore/gen_basestats. DO NOT EDIT.\n"

// f32 prints the shortest literal that reads back as the same float32, which is what the server
// computes with.
func f32(v float32) string {
	return strconv.FormatFloat(float64(v), 'g', -1, 32)
}

func crGoName(name string) string {
	var sb strings.Builder
	sb.WriteString("CR")
	for _, word := range strings.Split(name, "_") {
		sb.WriteString(word[:1] + strings.ToLower(word[1:]))
	}
	return sb.String()
}

func renderGo(m *model) ([]byte, error) {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	p("%s\n", header)
	p("// Level %d player stats from AzerothCore: the gt*.dbc game tables, the world database's\n", m.level)
	p("// player_class_stats and player_race_stats, and Unit.h, StatSystem.cpp and Player.cpp.\n\n")
	p("package core\n\n")
	p("import (\n\t\"github.com/wowsims/wotlk/sim/core/proto\"\n\t\"github.com/wowsims/wotlk/sim/core/stats\"\n)\n\n")

	p("// CombatRating is the server's CombatRating enum.\ntype CombatRating int32\n\nconst (\n")
	for i, r := range m.ratings {
		if i == 0 {
			p("\t%s CombatRating = iota\n", crGoName(r.Name))
		} else {
			p("\t%s\n", crGoName(r.Name))
		}
	}
	p("\tNumCombatRatings\n)\n\n")

	p("// Rating for 1%%, or for one point of defense or expertise. Every class converts these the same.\nconst (\n")
	for _, n := range namedRatings {
		if n.goName != "" {
			p("\t%s = %s\n", n.goName, f32(m.gt.combatRatings[m.rating(n.ratings[0])]))
		}
	}
	p(")\n\n")

	p("// Every class with mana shares these.\nconst (\n")
	p("\t// Spell crit chance per point of intellect (gtChanceToSpellCrit).\n")
	p("\tSpellCritPerIntellect = %s\n", f32(m.spellCritPerInt))
	p("\t// Mana per second per point of spirit, times √intellect (gtRegenMPPerSpt).\n")
	p("\tManaRegenPerSpirit = %s\n)\n\n", f32(m.manaRegenPerSpirit))

	p("// CombatRatingBase is gtCombatRatings: rating for 1%% before the class scalar.\n")
	p("var CombatRatingBase = [NumCombatRatings]float64{\n")
	for i, r := range m.ratings {
		p("\t%s: %s,\n", crGoName(r.Name), f32(m.gt.combatRatings[i]))
	}
	p("}\n\n")

	p("// CombatRatingClassScalars is gtOCTClassCombatRatingScalar, in CombatRating order. A class needs\n")
	p("// CombatRatingBase/scalar rating for 1%%.\n")
	p("var CombatRatingClassScalars = map[proto.Class][NumCombatRatings]float64{\n")
	for _, c := range classes {
		values := make([]string, len(m.ratings))
		for i := range values {
			values[i] = f32(m.gt.classScalars[c.serverID][i])
		}
		p("\tproto.Class_%s: {%s},\n", c.proto, strings.Join(values, ", "))
	}
	p("}\n\n")

	p("// ClassBaseStats is player_class_stats.\nvar ClassBaseStats = map[proto.Class]stats.Stats{\n")
	for _, c := range classes {
		s := m.classStats[c.serverID]
		p("\tproto.Class_%s: {stats.Health: %d, stats.Mana: %d, %s},\n", c.proto, s.BaseHP, s.BaseMana, goPrimaryStats(s.primaryStats))
	}
	p("}\n\n")

	p("// RaceStatOffsets is player_race_stats.\nvar RaceStatOffsets = map[proto.Race]stats.Stats{\n")
	for _, r := range races {
		p("\tproto.Race_%s: {%s},\n", r.proto, goPrimaryStats(m.raceStats[r.serverID]))
	}
	p("}\n\n")

	p("// ClassStatScaling comes from the gt crit tables, the attack power formulas in StatSystem.cpp,\n")
	p("// and the dodge and diminishing returns tables in Player.cpp and StatSystem.cpp.\n")
	p("var ClassStatScaling = map[proto.Class]StatScaling{\n")
	for _, c := range classes {
		i := c.serverID - 1
		p("\tproto.Class_%s: {\n", c.proto)
		for _, field := range []struct{ name, value string }{
			{"MeleeCritBase", f32(m.gt.meleeCritBase[c.serverID])},
			{"MeleeCritPerAgility", f32(m.gt.meleeCritPerAgi[c.serverID])},
			{"SpellCritBase", f32(m.gt.spellCritBase[c.serverID])},
			{"MeleeAttackPower", goFormula(m.meleeAP[c.serverID])},
			{"RangedAttackPower", goFormula(m.rangedAP[c.serverID])},
			{"DodgeBase", f32(m.dodgeBase[i])},
			{"CritToDodge", f32(m.critToDodge[i])},
			{"DodgeCap", f32(m.dodgeCap[i])},
			{"ParryCap", f32(m.parryCap[i])},
			{"MissCap", f32(m.missCap[i])},
			{"DiminishingK", f32(m.dimK[i])},
		} {
			p("\t\t%s: %s,\n", field.name, field.value)
		}
		p("\t},\n")
	}
	p("}\n")

	return format.Source([]byte(b.String()))
}

func goPrimaryStats(s primaryStats) string {
	return fmt.Sprintf("stats.Strength: %d, stats.Agility: %d, stats.Stamina: %d, stats.Intellect: %d, stats.Spirit: %d",
		s.Strength, s.Agility, s.Stamina, s.Intellect, s.Spirit)
}

func goFormula(f linearFormula) string {
	return fmt.Sprintf("AttackPowerFormula{PerLevel: %s, PerStrength: %s, PerAgility: %s, Base: %s}",
		f32(f.PerLevel), f32(f.PerStrength), f32(f.PerAgility), f32(f.Base))
}

func renderTS(m *model) []byte {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	p("%s\n", header)
	p("import { Class } from '../proto/common.js';\n\n")
	p("// Rating for 1%%, or for one point of defense or expertise, at level %d.\n", m.level)
	for _, n := range namedRatings {
		if n.tsName != "" {
			p("export const %s = %s;\n", n.tsName, f32(m.gt.combatRatings[m.rating(n.ratings[0])]))
		}
	}

	for _, s := range classScaledRatings {
		cr := m.rating(s.name)
		base := f32(m.gt.combatRatings[cr])
		p("\nexport const %s: Record<Class, number> = {\n", s.tsName)
		p("\t[Class.ClassUnknown]: %s,\n", base)
		for _, c := range classes {
			if scalar := m.gt.classScalars[c.serverID][cr]; scalar != 1 {
				p("\t[Class.%s]: %s / %s,\n", c.proto, base, f32(scalar))
			} else {
				p("\t[Class.%s]: %s,\n", c.proto, base)
			}
		}
		p("};\n")
	}
	return []byte(b.String())
}
